name: sea_battle
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  ansicolor: ^2.0.1
  bloc: ^7.0.0
  shelf_web_socket: ^1.0.1

dev_dependencies:
  pedantic: ^1.9.0


