name: sea_battle
description: Not a very simple command-line application.
version: 1.4.2

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  ansicolor: ^2.0.1
  argon2: ^1.0.1
  args: ^2.3.0
  bloc: ^7.2.1
  duration: ^3.0.7
  intl: ^0.17.0
  drift: ^1.0.1
  path: ^1.8.0
  shelf_web_socket: ^1.0.1

dev_dependencies:
  build_runner: ^2.1.4
  flutter_lints: ^1.0.4
  intl_generator: ^0.2.1
  intl_utils: ^2.4.1
  drift_dev: ^1.0.2
