name: sea_battle
description: Not a very simple command-line application.
version: 1.3.2
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  ansicolor: ^2.0.1
  argon2: ^1.0.1
  args: ^2.2.0
  bloc: ^7.0.0
  duration: ^3.0.6
  intl: ^0.17.0
  moor: ^4.4.1
  path: ^1.8.0
  shelf_web_socket: ^1.0.1

dev_dependencies:
  build_runner: ^2.0.6
  moor_generator: ^4.4.1
  pedantic: ^1.9.0
